import type { LP, Post, Comment, User } from "./types";

export const MOCK_LPS: LP[] = [
  {
    id: "lp-001",
    title: "201",
    artist: "검정치마",
    year: 2010,
    genre: "Indie Rock",
    label: "Pastel Music",
    coverUrl: "https://coverartarchive.org/release/9682220a-746d-47b0-9d69-52492e13dbad/23429647714-500.jpg",
    coverColor: "#152030",
    vinylStyle: "standard",
    playCount: 184200,
    youtubeId: "vOOYsBhzTKg",
    description:
      "2010 한국대중음악상 모던록 최우수 앨범상 수상작. 검정치마 첫 정규앨범으로, 날것의 인디록 감성과 독특한 멜로디가 공존하는 데뷔작.",
    externalPurchaseUrl: "#",
    tracks: [
      {
        id: "t-001-1",
        number: 1,
        title: "좋아해줘",
        duration: "3:45",
        side: "A",
        youtubeId: "vOOYsBhzTKg",
        lyrics: [
          { time: 0, text: "좋아해줘" },
          { time: 3, text: "내가 널 좋아해줘" },
          { time: 6, text: "너도 나를 좋아해줘" },
          { time: 9, text: "우리 같이 좋아해줘" },
          { time: 12, text: "좋아해줘" },
          { time: 15, text: "내가 널 좋아해줘" },
          { time: 18, text: "너도 나를 좋아해줘" },
          { time: 21, text: "우리 같이 좋아해줘" },
          { time: 24, text: "하늘을 보며" },
          { time: 27, text: "바람을 느끼며" },
          { time: 30, text: "우리 함께 걸어가" },
          { time: 33, text: "좋아해줘" },
          { time: 36, text: "내가 널 좋아해줘" },
          { time: 39, text: "너도 나를 좋아해줘" },
          { time: 42, text: "우리 같이 좋아해줘" },
          { time: 45, text: "좋아해줘" },
          { time: 48, text: "내가 널 좋아해줘" },
          { time: 51, text: "너도 나를 좋아해줘" },
          { time: 54, text: "우리 같이 좋아해줘" },
          { time: 57, text: "영원히 좋아해줘" },
          { time: 60, text: "우리 영원히" },
          { time: 63, text: "함일해줘" },
          { time: 66, text: "좋아해줘" },
          { time: 69, text: "내가 널 좋아해줘" },
          { time: 72, text: "너도 나를 좋아해줘" },
          { time: 75, text: "우리 같이 좋아해줘" },
          { time: 78, text: "좋아해줘" },
          { time: 81, text: "내가 널 좋아해줘" },
          { time: 84, text: "너도 나를 좋아해줘" },
          { time: 87, text: "우리 같이 좋아해줘" },
          { time: 90, text: "하늘을 보며" },
          { time: 93, text: "바람을 느끼며" },
          { time: 96, text: "우리 함께 걸어가" },
          { time: 99, text: "좋아해줘" },
          { time: 102, text: "내가 널 좋아해줘" },
          { time: 105, text: "너도 나를 좋아해줘" },
          { time: 108, text: "우리 같이 좋아해줘" },
          { time: 111, text: "좋아해줘" },
          { time: 114, text: "내가 널 좋아해줘" },
          { time: 117, text: "너도 나를 좋아해줘" },
          { time: 120, text: "우리 같이 좋아해줘" },
          { time: 123, text: "영원히 좋아해줘" },
          { time: 126, text: "우리 영원히" },
          { time: 129, text: "함일해줘" },
          { time: 132, text: "좋아해줘" },
          { time: 135, text: "내가 널 좋아해줘" },
          { time: 138, text: "너도 나를 좋아해줘" },
          { time: 141, text: "우리 같이 좋아해줘" },
          { time: 144, text: "좋아해줘" },
          { time: 147, text: "내가 널 좋아해줘" },
          { time: 150, text: "너도 나를 좋아해줘" },
          { time: 153, text: "우리 같이 좋아해줘" },
          { time: 156, text: "하늘을 보며" },
          { time: 159, text: "바람을 느끼며" },
          { time: 162, text: "우리 함께 걸어가" },
          { time: 165, text: "좋아해줘" },
          { time: 168, text: "내가 널 좋아해줘" },
          { time: 171, text: "너도 나를 좋아해줘" },
          { time: 174, text: "우리 같이 좋아해줘" },
          { time: 177, text: "좋아해줘" },
          { time: 180, text: "내가 널 좋아해줘" },
          { time: 183, text: "너도 나를 좋아해줘" },
          { time: 186, text: "우리 같이 좋아해줘" },
          { time: 189, text: "영원히 좋아해줘" },
          { time: 192, text: "우리 영원히" },
          { time: 195, text: "함일해줘" },
          { time: 198, text: "좋아해줘" },
          { time: 201, text: "내가 널 좋아해줘" },
          { time: 204, text: "너도 나를 좋아해줘" },
          { time: 207, text: "우리 같이 좋아해줘" },
          { time: 210, text: "좋아해줘" },
          { time: 213, text: "내가 널 좋아해줘" },
          { time: 216, text: "너도 나를 좋아해줘" },
          { time: 219, text: "우리 같이 좋아해줘" },
          { time: 222, text: "하늘을 보며" },
          { time: 225, text: "바람을 느끼며" },
          { time: 228, text: "우리 함께 걸어가" },
        ]
      },
      { id: "t-001-2",  number: 2,  title: "Stand Still",      duration: "4:12", side: "A", youtubeId: "L176COFLOZI" },
      { id: "t-001-3",  number: 3,  title: "강아지",           duration: "3:28", side: "A" },
      { id: "t-001-4",  number: 4,  title: "상아",             duration: "4:05", side: "A" },
      { id: "t-001-5",  number: 5,  title: "Antifreeze",       duration: "3:55", side: "A" },
      { id: "t-001-6",  number: 6,  title: "Tangled",          duration: "4:32", side: "B" },
      { id: "t-001-7",  number: 7,  title: "Avant Garde Kim",  duration: "3:18", side: "B" },
      { id: "t-001-8",  number: 8,  title: "Le Fou Muet",      duration: "5:04", side: "B" },
      { id: "t-001-9",  number: 9,  title: "Dientes",          duration: "3:47", side: "B" },
      { id: "t-001-10", number: 10, title: "Kiss And Tell",    duration: "4:20", side: "B" },
    ],
  },
  {
    id: "lp-002",
    title: "Don't You Worry Baby (I'm Only Swimming)",
    artist: "검정치마",
    year: 2011,
    genre: "Indie Rock",
    label: "Pastel Music",
    coverUrl: "https://coverartarchive.org/release/d335729c-188e-4eae-911a-0372c56bd01c/23486778417-500.jpg",
    coverColor: "#2a1020",
    vinylStyle: "color",
    playCount: 142800,
    youtubeId: "loysypSfVN0",
    description:
      "2011년 발매된 2집. 젊은 우리 사랑, International Love Song 등 검정치마 특유의 서정미가 담긴 앨범.",
    externalPurchaseUrl: "#",
    tracks: [
      { id: "t-002-1",  number: 1,  title: "이별노래",               duration: "3:42", side: "A" },
      { id: "t-002-2",  number: 2,  title: "무임승차",               duration: "4:05", side: "A" },
      { id: "t-002-3",  number: 3,  title: "Love Shine",             duration: "3:58", side: "A" },
      { id: "t-002-4",  number: 4,  title: "외아들",                 duration: "4:20", side: "A" },
      { id: "t-002-5",  number: 5,  title: "International Love Song", duration: "3:35", side: "A", youtubeId: "80nGOu5rCT0" },
      { id: "t-002-6",  number: 6,  title: "날씨",                   duration: "4:12", side: "A" },
      { id: "t-002-7",  number: 7,  title: "아침식사",               duration: "3:50", side: "B" },
      { id: "t-002-8",  number: 8,  title: "음악하는 여자",           duration: "4:08", side: "B" },
      { id: "t-002-9",  number: 9,  title: "젊은 우리 사랑",          duration: "3:55", side: "B", youtubeId: "loysypSfVN0" },
      { id: "t-002-10", number: 10, title: "Ariel",                  duration: "4:30", side: "B" },
      { id: "t-002-11", number: 11, title: "기사도",                 duration: "3:48", side: "B" },
      { id: "t-002-12", number: 12, title: "앵무새",                 duration: "4:15", side: "B" },
    ],
  },
  {
    id: "lp-003",
    title: "TEAM BABY",
    artist: "검정치마",
    year: 2017,
    genre: "Indie Pop",
    label: "Bespok",
    coverUrl: "https://coverartarchive.org/release/39579472-34ad-42b0-abfc-fa10203f2daa/41979713446-500.jpg",
    coverColor: "#3a1428",
    vinylStyle: "splatter",
    playCount: 218400,
    youtubeId: "Aq_gsctWHtQ",
    description:
      "3집 Part 1. 사랑과 낭만을 다양한 감성으로 담아낸 앨범. 타이틀곡 EVERYTHING을 포함한 10곡 수록.",
    externalPurchaseUrl: "#",
    tracks: [
      { id: "t-003-1",  number: 1,  title: "난 아니에요",            duration: "3:22", side: "A" },
      { id: "t-003-2",  number: 2,  title: "Big Love",              duration: "3:54", side: "A" },
      { id: "t-003-3",  number: 3,  title: "Diamond",               duration: "4:08", side: "A" },
      { id: "t-003-4",  number: 4,  title: "폭죽과 풍선들",          duration: "3:36", side: "A" },
      { id: "t-003-5",  number: 5,  title: "내 고향 서울엔",         duration: "4:15", side: "A" },
      { id: "t-003-6",  number: 6,  title: "Love Is All",           duration: "3:44", side: "B" },
      { id: "t-003-7",  number: 7,  title: "한시 오분 (1:05)",       duration: "4:30", side: "B" },
      { id: "t-003-8",  number: 8,  title: "나랑 아니면",            duration: "3:58", side: "B", youtubeId: "0dRo5Kbgx6c" },
      { id: "t-003-9",  number: 9,  title: "혜야",                  duration: "4:42", side: "B" },
      { id: "t-003-10", number: 10, title: "EVERYTHING",            duration: "4:18", side: "B", youtubeId: "HXV5aZaBLDo" },
    ],
  },
  {
    id: "lp-004",
    title: "THIRSTY",
    artist: "검정치마",
    year: 2019,
    genre: "Alt Rock",
    label: "Bespok",
    coverUrl: "https://coverartarchive.org/release/b3765e05-f348-4d33-8531-024d72604e70/29349624142-500.jpg",
    coverColor: "#3d0808",
    vinylStyle: "marble",
    playCount: 176300,
    youtubeId: "a_tMEXd8Zow",
    description:
      "3집 Part 2. 어둡고 갈증 어린 록 사운드로 채워진 앨범. 한국대중음악상 모던록 부문에 노미네이트.",
    externalPurchaseUrl: "#",
    tracks: [
      { id: "t-004-1",  number: 1,  title: "틀린질문",                       duration: "3:15", side: "A", youtubeId: "bi3lPMmK7Vk" },
      { id: "t-004-2",  number: 2,  title: "Lester Burnham",                 duration: "2:34", side: "A" },
      { id: "t-004-3",  number: 3,  title: "섬 (Queen of Diamonds)",          duration: "4:47", side: "A", youtubeId: "a_tMEXd8Zow" },
      { id: "t-004-4",  number: 4,  title: "상수역",                         duration: "3:07", side: "A" },
      { id: "t-004-5",  number: 5,  title: "광견일기",                        duration: "2:26", side: "A" },
      { id: "t-004-6",  number: 6,  title: "Bollywood",                      duration: "3:53", side: "B" },
      { id: "t-004-7",  number: 7,  title: "빨간 나를",                       duration: "4:31", side: "B" },
      { id: "t-004-8",  number: 8,  title: "Put Me On Drugs",                duration: "3:36", side: "B" },
      { id: "t-004-9",  number: 9,  title: "하와이 검은 모래",                duration: "4:16", side: "B", youtubeId: "b4Cy1OkrgUo" },
      { id: "t-004-10", number: 10, title: "맑고 묽게",                      duration: "4:55", side: "B" },
      { id: "t-004-11", number: 11, title: "그늘은 그림자로",                 duration: "4:47", side: "B" },
      { id: "t-004-12", number: 12, title: "피와 갈증 (King of Hurts)",      duration: "6:25", side: "B" },
    ],
  },
  {
    id: "lp-005",
    title: "Good Luck To You, Girl Scout!",
    artist: "검정치마",
    year: 2021,
    genre: "Indie Pop",
    label: "Bespok",
    coverUrl: "https://coverartarchive.org/release/2481f0a5-ed34-40a8-9470-a9437e9fe6bf/29349490763-500.jpg",
    coverColor: "#2a1a00",
    vinylStyle: "color",
    playCount: 98700,
    youtubeId: "xoRWoCvh6kc",
    description:
      "영어로 제작된 EP. 따뜻하고 감성적인 영미권 인디팝 사운드에 검정치마 특유의 감수성을 담아냈다.",
    externalPurchaseUrl: "#",
    tracks: [
      { id: "t-005-1", number: 1, title: "Good Luck To You, Girl Scout!", duration: "3:48", side: "A", youtubeId: "xoRWoCvh6kc" },
      { id: "t-005-2", number: 2, title: "Hollywood",                    duration: "3:22", side: "A" },
      { id: "t-005-3", number: 3, title: "Dream Like Me",               duration: "4:10", side: "A" },
      { id: "t-005-4", number: 4, title: "Fruit Fly",                   duration: "3:35", side: "B", youtubeId: "NqK7wwCYoq8" },
      { id: "t-005-5", number: 5, title: "Don't You Worry Baby",        duration: "4:55", side: "B" },
    ],
  },
  {
    id: "lp-006",
    title: "TEEN TROUBLES",
    artist: "검정치마",
    year: 2022,
    genre: "Indie Rock",
    label: "Bespok",
    coverUrl: "https://coverartarchive.org/release/8dfdb0ba-41fd-4b6a-a808-2c277d2067e5/41936084081-500.jpg",
    coverColor: "#1a2d45",
    vinylStyle: "color",
    playCount: 241600,
    youtubeId: "ar5l8SDXZpM",
    description:
      "3집 Part 3. 18곡에 걸쳐 청춘의 고민과 사랑, 방황을 록·팝·발라드로 풀어낸 집대성 앨범.",
    externalPurchaseUrl: "#",
    tracks: [
      { id: "t-006-1",  number: 1,  title: "Flying Bobs",               duration: "3:12", side: "A", youtubeId: "PlDudxUMAho" },
      { id: "t-006-2",  number: 2,  title: "Baptized In Fire (불세례)",  duration: "3:55", side: "A" },
      { id: "t-006-3",  number: 3,  title: "어린양",                    duration: "4:02", side: "A", youtubeId: "Yay61n44nA0" },
      { id: "t-006-4",  number: 4,  title: "Sunday Girl",               duration: "3:28", side: "A" },
      { id: "t-006-5",  number: 5,  title: "Friends In Bed",            duration: "3:44", side: "A" },
      { id: "t-006-6",  number: 6,  title: "Cicadas (매미들)",           duration: "4:15", side: "A" },
      { id: "t-006-7",  number: 7,  title: "Garden State Dreamers",     duration: "3:50", side: "A", youtubeId: "ar5l8SDXZpM" },
      { id: "t-006-8",  number: 8,  title: "Follow You (따라갈래)",      duration: "4:08", side: "A" },
      { id: "t-006-9",  number: 9,  title: "Jersey Girl",               duration: "3:33", side: "B" },
      { id: "t-006-10", number: 10, title: "Love You The Same",         duration: "4:20", side: "B" },
      { id: "t-006-11", number: 11, title: "Powder Blue",               duration: "3:46", side: "B" },
      { id: "t-006-12", number: 12, title: "Electra",                   duration: "4:00", side: "B" },
      { id: "t-006-13", number: 13, title: "Min (미는 남자)",            duration: "3:18", side: "B" },
      { id: "t-006-14", number: 14, title: "Jeff And Alana",            duration: "4:35", side: "B" },
      { id: "t-006-15", number: 15, title: "Ling Ling",                 duration: "3:22", side: "B" },
      { id: "t-006-16", number: 16, title: "John Fry",                  duration: "4:48", side: "B" },
      { id: "t-006-17", number: 17, title: "99%",                       duration: "3:55", side: "B" },
      { id: "t-006-18", number: 18, title: "Our Own Summer",            duration: "5:10", side: "B" },
    ],
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "c-1",
    userId: "u-1",
    nickname: "vinyl_lover",
    avatarColor: "#5B21B6",
    content: "Caroline 들을 때마다 심장이 쿵 내려앉아요. 검정치마 최고의 트랙 중 하나라고 생각해요.",
    timeAgo: "2시간 전",
    likeCount: 34,
  },
  {
    id: "c-2",
    userId: "u-2",
    nickname: "hol_fan",
    avatarColor: "#10B981",
    content: "THIRSTY 앨범 전체가 완벽해요. '피와 갈증' 마지막 파트에서 소름 돋음 ✨",
    timeAgo: "5시간 전",
    likeCount: 28,
  },
  {
    id: "c-3",
    userId: "u-3",
    nickname: "record_collector",
    avatarColor: "#F59E0B",
    content: "201 LP 실물로 들으면 진짜 다른 세계예요. 꼭 구해보세요!",
    timeAgo: "어제",
    likeCount: 12,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p-1",
    userId: "u-1",
    nickname: "vinyl_lover",
    avatarColor: "#5B21B6",
    title: "검정치마 201 LP 재발매판 드디어 구했어요",
    preview:
      "오랫동안 찾던 201 한정 LP 드디어 영입! 아날로그 특유의 따뜻한 그레인이 Antifreeze 인트로랑 너무 잘 어울려요. 조휴일의 목소리가 살아있는 것 같아요.",
    timeAgo: "1시간 전",
    likeCount: 62,
    commentCount: 18,
    tag: "LP 추천",
  },
  {
    id: "p-2",
    userId: "u-2",
    nickname: "hol_fan",
    avatarColor: "#10B981",
    title: "검정치마 입문 앨범 어떤 걸로 시작하면 좋을까요?",
    preview:
      "친구한테 검정치마를 소개해주고 싶은데 TEAM BABY로 시작할지 201로 시작할지 고민이에요. 각각 어떤 느낌인지 알려주세요!",
    timeAgo: "3시간 전",
    likeCount: 29,
    commentCount: 41,
    tag: "음악 이야기",
  },
  {
    id: "p-3",
    userId: "u-4",
    nickname: "crate_digger",
    avatarColor: "#EF4444",
    title: "TEEN TROUBLES 18곡 완주 후기 — 숨이 멎는 줄 알았어요",
    preview:
      "Garden State Dreamers에서 Our Own Summer까지 한 번에 들었는데 진짜 여름 내내 우울하고 행복했던 기억이 다 떠올랐어요.",
    timeAgo: "어제",
    likeCount: 113,
    commentCount: 47,
    tag: "앨범 리뷰",
  },
  {
    id: "p-4",
    userId: "u-5",
    nickname: "music_historian",
    avatarColor: "#3B82F6",
    title: "검정치마 전 앨범 완주 가이드 — 입문자를 위한 로드맵",
    preview:
      "201부터 TEEN TROUBLES까지 시대 순으로 듣는 방법을 정리했어요. 조휴일의 음악 세계가 어떻게 진화했는지 느껴보세요.",
    timeAgo: "2일 전",
    likeCount: 204,
    commentCount: 89,
    tag: "음악 이야기",
  },
];

export const MOCK_USER: User = {
  id: "u-me",
  nickname: "holideez_fan",
  bio: "검정치마 덕후. 조휴일 앨범 전부 LP로 갖고 있음 🖤",
  avatarColor: "#5B21B6",
  followerCount: 214,
  followingCount: 78,
  collectionCount: 6,
};

export const GENRES = [
  "전체", 
  "인디", 
  "인디 팝", 
  "얼터너티브 록", 
  "포크", 
  "재즈", 
  "일렉트로닉", 
  "힙합", 
  "클래식"
];

export function getLPById(id: string): LP | undefined {
  return MOCK_LPS.find((lp) => lp.id === id);
}
